### ISSUE TITLE
Memory leaks where Get<PrimitiveType>ArrayElements JNI routines are used

### ISSUE THREAD

**Issue by c42-arthur** [dogtagpki/jss#371]
There are various memory leaks where Get<PrimitiveType>ArrayElements JNI routines are used.

> Since the returned array may be a copy of the Java array, changes made to the returned array will not necessarily be reflected in the original array until Release<PrimitiveType>ArrayElements() is called.
>
> If isCopy is not NULL, then *isCopy is set to JNI_TRUE if a copy is made; or it is set to JNI_FALSE if no copy is made.

Reference https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html

This is a patch for an especially bad one.

```Index: org/mozilla/jss/pkcs11/PK11Cipher.c
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- org/mozilla/jss/pkcs11/PK11Cipher.c	(revision a7593745b6b71283c9ea6d95382edd758d3c1e3a)
+++ org/mozilla/jss/pkcs11/PK11Cipher.c	(revision 7121d4f82fa7c206fd15763e91528aabb8152396)
@@ -123,6 +123,7 @@
 {
     PK11Context *context=NULL;
     jbyte *inbuf=NULL;
+    jboolean inbufIsCopy;
     unsigned int inlen;
     unsigned char *outbuf=NULL;
     unsigned int outlen;
@@ -138,7 +139,7 @@
     /* extract input from byte array */
     inlen = (*env)->GetArrayLength(env, inputBA);
     PR_ASSERT(inlen >= 0);
-    inbuf = (*env)->GetByteArrayElements(env, inputBA, NULL);
+    inbuf = (*env)->GetByteArrayElements(env, inputBA, &inbufIsCopy);
     if(inbuf == NULL) {
         ASSERT_OUTOFMEM(env);
         goto finish;
@@ -173,6 +174,9 @@
     if(outbuf) {
         PR_Free(outbuf);
     }
+    if (inbuf && inbufIsCopy) {
+        PR_Free(inbuf);
+    }
     return outArray;
 }
 
```

**Comment by cipherboy** [comment]
@c42-arthur Agreed with the leaked memory. Thanks!

> ```diff
> +    jboolean inbufIsCopy;
> ```

My understanding from the JNI reference is that `(*env)->ReleaseByteArrayElements(...)` should always be called regardless of whether or not `isCopy` is true or false. I think it is incorrect (from the JSS PoV) to not call `Release...Elements`. 

> A family of functions that returns the body of the primitive array. The result is valid until the corresponding `Release<PrimitiveType>ArrayElements()` function is called.  
> If `isCopy` is not `NULL`, then `*isCopy` is set to `JNI_TRUE` if a copy is made; or it is set to `JNI_FALSE` if no copy is made.

Otherwise, when `isCopy` is `NULL`, it'd be a shot in the dark whether or not you'd know if you'd have to call `Release<Type>ArrayElements()`... which you wouldn't want. 

> ```diff 
> +        PR_Free(inbuf);
> ```

`PR_Free(...)` is Mozilla NSPR's free function. This shouldn't be called on JNI objects. On Linux, it is equivalent to `free(...)`, but on other platforms with other allocators, might not be the same as what Java is using. 

Regardless, I'll clean this up and propose it as a patch and ask for your review. Thanks again!

**Comment by cipherboy** [comment]
@c42-arthur I have a few other ideas for you about JSS and memory leaks if you want some more ideas and this patch isn't sufficient. Feel free to drop me an email.
